const foods = [
    {
        id: 1,
        name: "Chicken Sliders",
        price: "39.99",
        like: true,
        img: "https://awrestaurants.com/sites/default/files/2%20Chicken%20Sliders.png",
        category: "Chicken",
        about: "Juicy, 100% all white meat Hand-Breaded Chicken Tenders. Now in an even handier slider. Your choice of Hand-Breaded or Grilled.",
    },
    {
        id: 2,
        name: "Cod Sliders",
        price: "29.99",
        like: false,
        img: "https://awrestaurants.com/sites/default/files/Cod%20Slider.png",
        category: "Fish",
        about: "A golden-fried cod filet, tartar sauce, and dill pickles on a soft potato bun.",
    },
    {
        id: 1,
        name: "Chicken Sliders",
        price: "39.99",
        like: true,
        img: "https://awrestaurants.com/sites/default/files/2%20Chicken%20Sliders.png",
        category: "Chicken",
        about: "Juicy, 100% all white meat Hand-Breaded Chicken Tenders. Now in an even handier slider. Your choice of Hand-Breaded or Grilled.",
    },
    {
        id: 2,
        name: "Cod Sliders",
        price: "29.99",
        like: false,
        img: "https://awrestaurants.com/sites/default/files/Cod%20Slider.png",
        category: "Fish",
        about: "A golden-fried cod filet, tartar sauce, and dill pickles on a soft potato bun.",
    },
    {
        id: 1,
        name: "Chicken Sliders",
        price: "39.99",
        like: true,
        img: "https://awrestaurants.com/sites/default/files/2%20Chicken%20Sliders.png",
        category: "Chicken",
        about: "Juicy, 100% all white meat Hand-Breaded Chicken Tenders. Now in an even handier slider. Your choice of Hand-Breaded or Grilled.",
    },
    {
        id: 2,
        name: "Cod Sliders",
        price: "29.99",
        like: false,
        img: "https://awrestaurants.com/sites/default/files/Cod%20Slider.png",
        category: "Fish",
        about: "A golden-fried cod filet, tartar sauce, and dill pickles on a soft potato bun.",
    },
    {
        id: 1,
        name: "Chicken Sliders",
        price: "39.99",
        like: true,
        img: "https://awrestaurants.com/sites/default/files/2%20Chicken%20Sliders.png",
        category: "Chicken",
        about: "Juicy, 100% all white meat Hand-Breaded Chicken Tenders. Now in an even handier slider. Your choice of Hand-Breaded or Grilled.",
    },
    {
        id: 2,
        name: "Cod Sliders",
        price: "29.99",
        like: false,
        img: "https://awrestaurants.com/sites/default/files/Cod%20Slider.png",
        category: "Fish",
        about: "A golden-fried cod filet, tartar sauce, and dill pickles on a soft potato bun.",
    },
];

export default foods;
